/** Sentinel: show companion text field; must not be a valid stored profile value. */
export const DEMO_CUSTOM = "__custom__";

export type LabeledValue = { value: string; label: string };

/** One option per year (API stores a single integer `birth_year`). */
export function birthYearOptions(): LabeledValue[] {
  const max = new Date().getFullYear();
  const out: LabeledValue[] = [{ value: "", label: "Prefer not to say / skip" }];
  for (let y = max; y >= 1900; y--) {
    out.push({ value: String(y), label: String(y) });
  }
  return out;
}

export const LOCALE_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  { value: "en-US", label: "English — United States (en-US)" },
  { value: "en-GB", label: "English — United Kingdom (en-GB)" },
  { value: "en-AU", label: "English — Australia (en-AU)" },
  { value: "en-CA", label: "English — Canada (en-CA)" },
  { value: "en-NZ", label: "English — New Zealand (en-NZ)" },
  { value: "en-IE", label: "English — Ireland (en-IE)" },
  { value: "en-IN", label: "English — India (en-IN)" },
  { value: "en-ZA", label: "English — South Africa (en-ZA)" },
  { value: "en-SG", label: "English — Singapore (en-SG)" },
  { value: "en-PH", label: "English — Philippines (en-PH)" },
  { value: "en-NG", label: "English — Nigeria (en-NG)" },
  { value: "en-KE", label: "English — Kenya (en-KE)" },
  { value: "es-ES", label: "Spanish — Spain (es-ES)" },
  { value: "es-MX", label: "Spanish — Mexico (es-MX)" },
  { value: "es-AR", label: "Spanish — Argentina (es-AR)" },
  { value: "es-CO", label: "Spanish — Colombia (es-CO)" },
  { value: "es-CL", label: "Spanish — Chile (es-CL)" },
  { value: "es-US", label: "Spanish — United States (es-US)" },
  { value: "fr-FR", label: "French — France (fr-FR)" },
  { value: "fr-CA", label: "French — Canada (fr-CA)" },
  { value: "fr-BE", label: "French — Belgium (fr-BE)" },
  { value: "fr-CH", label: "French — Switzerland (fr-CH)" },
  { value: "de-DE", label: "German — Germany (de-DE)" },
  { value: "de-AT", label: "German — Austria (de-AT)" },
  { value: "de-CH", label: "German — Switzerland (de-CH)" },
  { value: "it-IT", label: "Italian — Italy (it-IT)" },
  { value: "it-CH", label: "Italian — Switzerland (it-CH)" },
  { value: "pt-BR", label: "Portuguese — Brazil (pt-BR)" },
  { value: "pt-PT", label: "Portuguese — Portugal (pt-PT)" },
  { value: "nl-NL", label: "Dutch — Netherlands (nl-NL)" },
  { value: "nl-BE", label: "Dutch — Belgium (nl-BE)" },
  { value: "sv-SE", label: "Swedish — Sweden (sv-SE)" },
  { value: "no-NO", label: "Norwegian — Norway (no-NO)" },
  { value: "nb-NO", label: "Norwegian Bokmål (nb-NO)" },
  { value: "da-DK", label: "Danish — Denmark (da-DK)" },
  { value: "fi-FI", label: "Finnish — Finland (fi-FI)" },
  { value: "is-IS", label: "Icelandic — Iceland (is-IS)" },
  { value: "pl-PL", label: "Polish — Poland (pl-PL)" },
  { value: "cs-CZ", label: "Czech — Czechia (cs-CZ)" },
  { value: "sk-SK", label: "Slovak — Slovakia (sk-SK)" },
  { value: "hu-HU", label: "Hungarian — Hungary (hu-HU)" },
  { value: "ro-RO", label: "Romanian — Romania (ro-RO)" },
  { value: "bg-BG", label: "Bulgarian — Bulgaria (bg-BG)" },
  { value: "el-GR", label: "Greek — Greece (el-GR)" },
  { value: "tr-TR", label: "Turkish — Türkiye (tr-TR)" },
  { value: "ru-RU", label: "Russian — Russia (ru-RU)" },
  { value: "uk-UA", label: "Ukrainian — Ukraine (uk-UA)" },
  { value: "be-BY", label: "Belarusian — Belarus (be-BY)" },
  { value: "ja-JP", label: "Japanese — Japan (ja-JP)" },
  { value: "ko-KR", label: "Korean — South Korea (ko-KR)" },
  { value: "zh-CN", label: "Chinese — China, simplified (zh-CN)" },
  { value: "zh-TW", label: "Chinese — Taiwan, traditional (zh-TW)" },
  { value: "zh-HK", label: "Chinese — Hong Kong (zh-HK)" },
  { value: "hi-IN", label: "Hindi — India (hi-IN)" },
  { value: "bn-BD", label: "Bengali — Bangladesh (bn-BD)" },
  { value: "ta-IN", label: "Tamil — India (ta-IN)" },
  { value: "th-TH", label: "Thai — Thailand (th-TH)" },
  { value: "vi-VN", label: "Vietnamese — Vietnam (vi-VN)" },
  { value: "id-ID", label: "Indonesian — Indonesia (id-ID)" },
  { value: "ms-MY", label: "Malay — Malaysia (ms-MY)" },
  { value: "fil-PH", label: "Filipino — Philippines (fil-PH)" },
  { value: "ar-SA", label: "Arabic — Saudi Arabia (ar-SA)" },
  { value: "ar-AE", label: "Arabic — UAE (ar-AE)" },
  { value: "ar-EG", label: "Arabic — Egypt (ar-EG)" },
  { value: "he-IL", label: "Hebrew — Israel (he-IL)" },
  { value: "fa-IR", label: "Persian — Iran (fa-IR)" },
  { value: "ur-PK", label: "Urdu — Pakistan (ur-PK)" },
  { value: "sw-KE", label: "Swahili — Kenya (sw-KE)" },
  { value: "af-ZA", label: "Afrikaans — South Africa (af-ZA)" },
  { value: "zu-ZA", label: "Zulu — South Africa (zu-ZA)" },
  { value: DEMO_CUSTOM, label: "Other — I’ll type a BCP-47 tag below" },
];

export const GENDER_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  { value: "Woman", label: "Woman" },
  { value: "Man", label: "Man" },
  { value: "Non-binary", label: "Non-binary" },
  { value: "Genderfluid", label: "Genderfluid" },
  { value: "Agender", label: "Agender" },
  { value: "Bigender", label: "Bigender" },
  { value: "Demigirl", label: "Demigirl" },
  { value: "Demiboy", label: "Demiboy" },
  { value: "Two-Spirit", label: "Two-Spirit" },
  { value: "Transgender woman", label: "Transgender woman" },
  { value: "Transgender man", label: "Transgender man" },
  { value: "Questioning or exploring", label: "Questioning or exploring" },
  { value: "Prefer not to label", label: "Prefer not to label" },
  { value: DEMO_CUSTOM, label: "Something else — describe in my own words" },
];

export const OCCUPATION_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  { value: "Software engineer / developer", label: "Software engineer / developer" },
  { value: "Engineering manager", label: "Engineering manager" },
  { value: "Product manager", label: "Product manager" },
  { value: "Product designer (UX/UI)", label: "Product designer (UX/UI)" },
  { value: "Data scientist / ML engineer", label: "Data scientist / ML engineer" },
  { value: "Data analyst / BI", label: "Data analyst / BI" },
  { value: "DevOps / SRE / Platform", label: "DevOps / SRE / Platform" },
  { value: "QA / Test engineer", label: "QA / Test engineer" },
  { value: "Technical writer", label: "Technical writer" },
  { value: "IT support / sysadmin", label: "IT support / sysadmin" },
  { value: "Information security", label: "Information security" },
  { value: "Founder / co-founder", label: "Founder / co-founder" },
  { value: "CEO / executive", label: "CEO / executive" },
  { value: "Consultant (technology)", label: "Consultant (technology)" },
  { value: "Consultant (non-tech)", label: "Consultant (non-tech)" },
  { value: "Freelancer / contractor", label: "Freelancer / contractor" },
  { value: "Sales / business development", label: "Sales / business development" },
  { value: "Marketing / growth", label: "Marketing / growth" },
  { value: "Customer success / support", label: "Customer success / support" },
  { value: "Operations / COO office", label: "Operations / COO office" },
  { value: "Finance / accounting", label: "Finance / accounting" },
  { value: "Legal / compliance", label: "Legal / compliance" },
  { value: "HR / people ops", label: "HR / people ops" },
  { value: "Recruiter / talent", label: "Recruiter / talent" },
  { value: "Researcher (academic)", label: "Researcher (academic)" },
  { value: "Scientist / lab", label: "Scientist / lab" },
  { value: "Physician / clinician", label: "Physician / clinician" },
  { value: "Nurse / allied health", label: "Nurse / allied health" },
  { value: "Teacher / lecturer", label: "Teacher / lecturer" },
  { value: "Student (university)", label: "Student (university)" },
  { value: "Student (secondary)", label: "Student (secondary)" },
  { value: "Artist / creative", label: "Artist / creative" },
  { value: "Writer / editor / journalist", label: "Writer / editor / journalist" },
  { value: "Architect / civil engineer", label: "Architect / civil engineer" },
  { value: "Skilled trades", label: "Skilled trades" },
  { value: "Retail / hospitality", label: "Retail / hospitality" },
  { value: "Government / public sector", label: "Government / public sector" },
  { value: "Non-profit / charity", label: "Non-profit / charity" },
  { value: "Homemaker / caregiver", label: "Homemaker / caregiver" },
  { value: "Retired", label: "Retired" },
  { value: "Between roles", label: "Between roles" },
  { value: DEMO_CUSTOM, label: "Other — specify below" },
];

export const INDUSTRY_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  { value: "Technology / software", label: "Technology / software" },
  { value: "Internet / digital media", label: "Internet / digital media" },
  { value: "Financial services / fintech", label: "Financial services / fintech" },
  { value: "Insurance", label: "Insurance" },
  { value: "Healthcare / health tech", label: "Healthcare / health tech" },
  { value: "Pharma / biotech", label: "Pharma / biotech" },
  { value: "Education / edtech", label: "Education / edtech" },
  { value: "Government / public administration", label: "Government / public administration" },
  { value: "Defense / aerospace", label: "Defense / aerospace" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Automotive", label: "Automotive" },
  { value: "Energy / utilities", label: "Energy / utilities" },
  { value: "Construction / real estate", label: "Construction / real estate" },
  { value: "Retail / e-commerce", label: "Retail / e-commerce" },
  { value: "Hospitality / travel", label: "Hospitality / travel" },
  { value: "Media / entertainment", label: "Media / entertainment" },
  { value: "Advertising / marketing agency", label: "Advertising / marketing agency" },
  { value: "Legal services", label: "Legal services" },
  { value: "Professional services (consulting)", label: "Professional services (consulting)" },
  { value: "Accounting / audit", label: "Accounting / audit" },
  { value: "Agriculture / food production", label: "Agriculture / food production" },
  { value: "Logistics / supply chain", label: "Logistics / supply chain" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Non-profit / NGO", label: "Non-profit / NGO" },
  { value: "Religious organization", label: "Religious organization" },
  { value: "Sports / fitness", label: "Sports / fitness" },
  { value: "Gaming / esports", label: "Gaming / esports" },
  { value: "Arts / culture", label: "Arts / culture" },
  { value: "Other / not listed", label: "Other / not listed" },
  { value: DEMO_CUSTOM, label: "Other — describe below" },
];

export const WORK_ROLE_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  { value: "Individual contributor", label: "Individual contributor" },
  { value: "Senior IC / staff / principal", label: "Senior IC / staff / principal" },
  { value: "Tech lead / lead", label: "Tech lead / lead" },
  { value: "Team lead", label: "Team lead" },
  { value: "Manager (people manager)", label: "Manager (people manager)" },
  { value: "Senior manager / head of", label: "Senior manager / head of" },
  { value: "Director", label: "Director" },
  { value: "VP / SVP", label: "VP / SVP" },
  { value: "C-level (CEO, CTO, …)", label: "C-level (CEO, CTO, …)" },
  { value: "Founder / owner", label: "Founder / owner" },
  { value: "Board / advisor", label: "Board / advisor" },
  { value: "Intern / apprentice", label: "Intern / apprentice" },
  { value: "Freelancer / self-employed", label: "Freelancer / self-employed" },
  { value: "Student", label: "Student" },
  { value: "Educator / faculty", label: "Educator / faculty" },
  { value: DEMO_CUSTOM, label: "Other — specify below" },
];

export const PRIMARY_USE_CASE_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  {
    value: "Personal accountability — honest picture of where my time goes vs intentions",
    label: "Personal accountability — honest picture of where my time goes vs intentions",
  },
  {
    value: "Deep work / focus — reduce context switching and distraction",
    label: "Deep work / focus — reduce context switching and distraction",
  },
  {
    value: "Building better daily habits and streaks",
    label: "Building better daily habits and streaks",
  },
  {
    value: "End-of-day reflection and AI summaries",
    label: "End-of-day reflection and AI summaries",
  },
  {
    value: "Team visibility — friendly leaderboard with colleagues",
    label: "Team visibility — friendly leaderboard with colleagues",
  },
  {
    value: "Reporting to manager or coach (export / evidence of focus time)",
    label: "Reporting to manager or coach (export / evidence of focus time)",
  },
  {
    value: "Billing or client time (rough sense of hours on work sites)",
    label: "Billing or client time (rough sense of hours on work sites)",
  },
  {
    value: "Research / PhD — track reading and writing sessions",
    label: "Research / PhD — track reading and writing sessions",
  },
  {
    value: "Studying — exam prep and course work",
    label: "Studying — exam prep and course work",
  },
  {
    value: "ADHD / attention patterns — self-awareness without shame",
    label: "ADHD / attention patterns — self-awareness without shame",
  },
  {
    value: "Digital wellbeing — less mindless browsing",
    label: "Digital wellbeing — less mindless browsing",
  },
  {
    value: "Trying the product before recommending to my team",
    label: "Trying the product before recommending to my team",
  },
  { value: DEMO_CUSTOM, label: "Something else — I’ll describe below" },
];

export const REFERRAL_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  { value: "Google / web search", label: "Google / web search" },
  { value: "Friend or colleague", label: "Friend or colleague" },
  { value: "LinkedIn", label: "LinkedIn" },
  { value: "Twitter / X", label: "Twitter / X" },
  { value: "Bluesky", label: "Bluesky" },
  { value: "Mastodon", label: "Mastodon" },
  { value: "Reddit", label: "Reddit" },
  { value: "Hacker News", label: "Hacker News" },
  { value: "YouTube", label: "YouTube" },
  { value: "TikTok", label: "TikTok" },
  { value: "Instagram", label: "Instagram" },
  { value: "Podcast", label: "Podcast" },
  { value: "Newsletter / email", label: "Newsletter / email" },
  { value: "Chrome Web Store", label: "Chrome Web Store" },
  { value: "GitHub / open source", label: "GitHub / open source" },
  { value: "Product Hunt", label: "Product Hunt" },
  { value: "Conference or meetup", label: "Conference or meetup" },
  { value: "University / bootcamp", label: "University / bootcamp" },
  { value: "Employer / internal tool list", label: "Employer / internal tool list" },
  { value: DEMO_CUSTOM, label: "Other — tell us below" },
];

export const COMPANY_SIZE_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  { value: "1", label: "Just me (solo)" },
  { value: "2-10", label: "2 – 10 people" },
  { value: "11-50", label: "11 – 50" },
  { value: "51-200", label: "51 – 200" },
  { value: "201+", label: "201+" },
  { value: "prefer_not_say", label: "Prefer not to say (explicit)" },
];

/** ISO 3166-1 alpha-2 — common + comprehensive; labels for readability in UI. */
export const COUNTRY_OPTIONS: LabeledValue[] = [
  { value: "", label: "Prefer not to say / skip" },
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brazil" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CV", label: "Cape Verde" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "Congo (DRC)" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d’Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czechia" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "SZ", label: "Eswatini" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Greece" },
  { value: "GD", label: "Grenada" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-Bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "XK", label: "Kosovo" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Laos" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macao" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia" },
  { value: "MD", label: "Moldova" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "KP", label: "North Korea" },
  { value: "MK", label: "North Macedonia" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestine" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russia" },
  { value: "RW", label: "Rwanda" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "São Tomé and Príncipe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "KR", label: "South Korea" },
  { value: "SS", label: "South Sudan" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syria" },
  { value: "TW", label: "Taiwan" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-Leste" },
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Türkiye" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatican City" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Vietnam" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
  { value: DEMO_CUSTOM, label: "Other — type 2-letter ISO code below" },
];

export function resolveSelect(
  saved: string | null | undefined,
  options: LabeledValue[],
  customToken: string
): { select: string; other: string } {
  if (!saved) return { select: "", other: "" };
  const allowed = new Set(
    options.map((o) => o.value).filter((v) => v !== "" && v !== customToken)
  );
  if (allowed.has(saved)) return { select: saved, other: "" };
  return { select: customToken, other: saved };
}

export function mergeSelectOrCustom(select: string, other: string, customToken: string): string | null {
  if (!select) return null;
  if (select === customToken) {
    const t = other.trim();
    return t === "" ? null : t;
  }
  return select;
}
